spring.application.name=catalogo

# Configura\u00e7\u00e3o do PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/CatalogoStreaming
spring.datasource.username=postgres
spring.datasource.password=05092005Gle!
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Mostrar SQL no console
spring.jpa.show-sql=true

# Formatar as SQLs no console
spring.jpa.properties.hibernate.format_sql=true


spring.jpa.hibernate.ddl-auto=update

server.port=8081
#usar a sintaxe do postegre
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect